version: '3.8'

services:
  app:
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: ["sh", "/entrypoint.sh"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: app-db
    ports:
      - "5432:5432"
    build:
      dockerfile: Dockerfile
      target: postgres_migration
      context: .
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
    { }

networks:
  app-network: