# Test your FastAPI endpoints

### Creating a URL object
POST http://localhost:8000/
Content-Type: application/json

{
  "full_url": "https://example.com"
}

###

### Redirect to full URL ###
GET http://localhost:8000/c984/
Content-Type: application/json

###

### Deleting a URL object ###
DELETE http://localhost:8000/c984/
Content-Type: application/json

###